site_name: 'test-1hicon'
site_description: 'Main documentation for the test-1hicon'
repo_url: https://github.com/HICONNOS/test-1hicon
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'index.md'